[package]
name = "fcmc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = "0.19.8"
regex = "1.7.1"

[build-dependencies]
lalrpop = "0.19.8"
